toml
[package]
name = "image_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
actix-web = "4"